from typing import List, Optional
from pydantic import BaseModel, Field

class Source(BaseModel):
    """
    Represents a source document retrieved from the knowledge base.
    """
    id: str = Field(description="Unique identifier of the source document.")
    content: str = Field(description="The actual text content retrieved.")
    score: Optional[float] = Field(default=None, description="Similarity score of the document if available.")

class ChatRequest(BaseModel):
    """
    Incoming request model for the chat API.
    """
    question: str = Field(description="The user's question or message.")

class ChatResponse(BaseModel):
    """
    Outgoing response model for the chat API.
    """
    answer: str = Field(description="The final answer generated by the agent.")
    sources: List[Source] = Field(default_factory=list, description="List of sources used to generate the answer.")
