from langchain_core.messages import HumanMessage
from application.agents.graph import graph
from application.dto.chat_models import ChatRequest, ChatResponse, Source
from typing import AsyncGenerator

class ChatService:
    """
    Application Service layer handling the chat use case operations.
    Bridges the gap between external interfaces (API/CLI) and the 
    Agentic Workflow (LangGraph).
    """

    @staticmethod
    async def ask_question(request: ChatRequest) -> ChatResponse:
        """
        Synchronously resolves fully generated response from the agent.
        (Called using `graph.astream` yielding complete chunks under the hood)
        """
        inputs = {"messages": [HumanMessage(content=request.question)]}
        final_message = ""
        
        # Traverse the state graph synchronously for end-result
        async for event in graph.astream(inputs, stream_mode="values"):
            message = event["messages"][-1]
            final_message = message.content

        # Since we haven't implemented explicit citation gathering in the agent yet,
        # we return an empty sources array for now.
        return ChatResponse(
            answer=final_message,
            sources=[]
        )

    @staticmethod
    async def stream_question(request: ChatRequest) -> AsyncGenerator[str, None]:
        """
        Streams only the text tokens generated by the LLM inside the Agent workflow.
        """
        inputs = {"messages": [HumanMessage(content=request.question)]}
        
        async for event in graph.astream_events(inputs, version="v2"):
            kind = event["event"]
            if kind == "on_chat_model_stream":
                chunk = event["data"]["chunk"].content
                if chunk:
                    yield chunk
