from fastapi import FastAPI
from fastapi.responses import StreamingResponse
from dotenv import load_dotenv

from application.services.chat_service import ChatService
from application.dto.chat_models import ChatRequest, ChatResponse
import uvicorn

# Load API keys
load_dotenv()

app = FastAPI(title="Agentic RAG API", version="1.1.0")

@app.post("/ask", response_model=ChatResponse)
async def ask_agent(request: ChatRequest):
    """
    Endpoint communicating with the LangGraph Agentic RAG.
    """
    response = await ChatService.ask_question(request)
    return response

@app.post("/ask/stream")
async def ask_agent_stream(request: ChatRequest):
    """
    Streaming endpoint communicating with LangGraph Agentic RAG.
    Yields parsed tokens as they are generated by the LLM.
    """
    return StreamingResponse(ChatService.stream_question(request), media_type="text/event-stream")

if __name__ == "__main__":
    uvicorn.run("api.main:app", host="0.0.0.0", port=8000, reload=True)
